stages:
    - test
    - build
    - deploy

services:
    - docker:dind
# Run flake8 to check for code quality
lint-test-job:
    image: python:3-bullseye
    stage: test
    script:
        - pip install flake8
        - flake8 cookit
#
# # Run the unit tests
api-unit-tests-job:
    image: python:3-bullseye
    stage: test
    script:
        - cd cookit
        - pip install -r requirements.txt
        - python -m pytest

# # Build the React/JavaScript front-end
build-front-end-job:
    stage: build
    image: node:lts-bullseye
    needs:
        - api-unit-tests-job
        - lint-test-job
    variables:
        # If either of these variables is defined in the GitLab
        # CI/CD variables, that value will override the value here.
        # You need to substitute in your real values for
        # GROUP_NAME, PROJECT_NAME, & WEBSERVICE_NAME below.
        PUBLIC_URL: https://nmichtavy.gitlab.io/module3-project-gamma
        REACT_APP_COOKIT_API_HOST: https://feb-23-et-6-cookit.mod3projects.com
    script:
        - cd ghi
        - npm install
        - npm run build
        - cp build/index.html build/404.html
    artifacts:
        paths:
            - ghi/build/

# # Deploy the React/JavaScript front-end to GitLab pages
pages:
    stage: deploy
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    dependencies:
        - build-front-end-job
    needs:
        - build-front-end-job
    script:
        - mv ghi/build/ public
    artifacts:
        paths:
            - public

build-muscle-up-image:
    stage: build
    image: docker:git
    variables:
        GITLAB_IMAGE: ${CI_REGISTRY_IMAGE}/cookit
    before_script:
        # $CI_JOB_TOKEN is variable automatically added by Gitlab: see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    script:
        - docker build --tag $GITLAB_IMAGE:latest cookit
        - docker push $GITLAB_IMAGE:latest
    only:
        - main

deploy-muscle-up-image:
    stage: deploy
    image: registry.gitlab.com/galvanize-inc/foss/glv-cloud-cli:latest
    script:
        - glv-cloud-cli reset -a ${COOK_IT_API} -t ${CIRRUS_TOKEN}
    only:
        - main
